name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "**/*.md"
      - "**/*.svg"
      - "**.svg"
    branches:
      - "master"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**/*.md"
      - "**/*.svg"
      - "**.svg"
    branches:
      - "master"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ["18.x", "19.x", "20.x", "21.x", "22.x", "23.x"]
    runs-on: ${{ matrix.os }}
    name: Optimize & Build - v${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        run: npm i -g pnpm@9.10.0 && pnpm -v

      - name: Install Dependencies
        run: pnpm i

      - name: Optimize & Build
        run: pnpm run optimize && pnpm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: temp-artifacts
          path: dist

      - name: Upload Successful Summary
        if: success()
        run: echo "Build Succeeded ✅"

      - name: Upload Failure Summary
        if: failure()
        run: echo "Build Failed ❌"