name: CI / Generate Statistics

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  stats:
    name: Generate Stats
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Import GPG Key
      id: gpg
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
        git_config_global: true
        git_push_gpgsign: true
        trust_level: 5

    - name: Verify GPG Key
      run: |
        gpg --list-secret-keys --keyid-format LONG
        git config --global --list

    - name: Generate Stats
      uses: offensive-vk/auto-stats@v6
      with:
        options: '-A -S'
        name: Hamster [bot]
        email: TheHamsterBot@outlook.com
        branch: master
        message: 'Updated Repo Stats - Hamster 🐹'
        github-token: ${{ secrets.BOT_TOKEN || secrets.GITHUB_TOKEN }}